site_name: "Sharky's VRC Avatar Utils"
site_description: "A growing collection of tools to help in creating, editing and uploading Avatars for VRChat."
site_author: "SharkyTheWhite"
docs_dir: "."
site_dir: "../site"
